### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by bostick**
Fix a handful of simple typos

### CODE REVIEW

**Comment by bostick** [comment]
Any interest in typo fixes?

**Comment by Jamim** [comment]
_Hello @bostick,_

It's sad that you gave up and closed this PR. Unfortunately, it had not chance of being merged here since this repository is [just a mirror](https://github.com/sqlite/sqlite/blob/master/README.md?plain=1#L15-L16). I understand how frustrating it would be to waste time like this, so I've started this discussion on the SQLite Forum:
  * [GitHub PR template](https://sqlite.org/forum/forumpost/3a4bb42772)

You can share your thoughts there, if you want to.

_Best regards!_

**Comment by bostick** [comment]
I realized GitHub repo is just a mirror and the PR was not going to be merged on GitHub, so closed it. Whatever is the correct way to submit changes, SQLite seems pretty hostile to contributions, and I just don't have the energy to fight that.

> SQLite is "Open-Source, not Open-Contribution"

> "the project does not accept patches".

Talking about an affidavit on [this](https://www.sqlite.org/copyright.html) page, but not providing a way sign it.

Seems clear that contributions of any form are not welcome. Oh well

**Comment by musvaage** [comment]
backup.c
bitvec.c
btree.c
pager.c
pcache.c
whereInt.h

British spelling is with a double `l`.

**Pull request closed without merging**
